language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install: "pip install -r requirements.txt"
script: "python -m unittest discover"
branches:
    only:
        # For now, only the tests branch is able to be tested.
        - tests
